# Generated by Django 4.2.4 on 2023-08-26 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AIverse', '0003_alter_aiverse_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiverse',
            old_name='team_member',
            new_name='Team_member',
        ),
        migrations.AddField(
            model_name='aiverse',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiverse',
            name='Screenshot',
            field=models.ImageField(null=True, upload_to='Event/images'),
        ),
        migrations.AlterField(
            model_name='aiverse',
            name='Transaction',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
