# Generated by Django 4.2.4 on 2023-08-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIverse', '0004_rename_team_member_aiverse_team_member_aiverse_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiverse',
            old_name='Transaction',
            new_name='Transaction_ID',
        ),
    ]
