# Generated by Django 4.2.4 on 2023-08-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIverse', '0005_rename_transaction_aiverse_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiverse',
            name='Sr_no',
        ),
        migrations.AddField(
            model_name='aiverse',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiverse',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
